# Generated by Django 4.0.4 on 2022-04-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('Roll_num', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
